M48
; DRILL file {KiCad 9.0.0} date 2026-02-24T22:35:43+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-24T22:35:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.5789Y-2.9374
X4.5789Y-3.165
T2
X6.0236Y-3.3268
M30
